### ISSUE TITLE
No IM set as provider -> current username/password form needs to be shown

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-authorization-server#20]
In the current system, if the provider is set in oauth2.providers and there is the client-id for that provider (see [https://github.com/intermine/intermine/blob/dev/intermine/webapp/src/main/java/org/intermine/web/struts/InitialiserPlugin.java#L713]), is added to OAUTH2_PROVIDERS and then displayed in the login form.
If there is IM, the current username password WILL NOT BE showed; the option will appear in the drop down list.

**Comment by danielabutano** [comment]
@rahul-y we discussed via email. slightly change here https://github.com/rahul-y/intermine/blob/migration/intermine/webapp/src/main/webapp/WEB-INF/tags/login.tag#L28
the dropdown only and only if we have IM otherwise login form and login form can contain google or exilr button

**Comment by rahul-y** [comment]
Check it out now --> [commit](https://github.com/rahul-y/intermine/commit/b693bd7f414cf7a920887e88bea943472f9a59e3)

**Comment by danielabutano** [comment]
Great!
