### ISSUE TITLE
Two entries in the userprofile table with same username, during the merging

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-authorization-server#21]
Before updating the profile, add check there is no an user with the same username already.

**Comment by danielabutano** [comment]
@rahul-y I think it's much much  safer if before updating the profile username with the new IM:sub https://github.com/rahul-y/intermine/blob/migration/intermine/api/src/main/java/org/intermine/api/profile/ProfileManager.java#L1634 we first check that there is not already a user with that username to prevent to have 2 entries with the same username!!!

**Comment by rahul-y** [comment]
https://github.com/rahul-y/intermine/blob/0101946b3ddbf7400f4e00b6cd54f07619b20f2c/intermine/api/src/main/java/org/intermine/api/profile/ProfileManager.java#L1373

we are checking already :)

**Comment by danielabutano** [comment]
@rahul-y  ok, great! Please could you just add a info log (if profile=null) saying there is already a user and specify the username. Thanks!

**Comment by danielabutano** [comment]
@rahul-y please also add the check in the updateProfile function, in the future this might be used by other classes and would prefer the check inside the method. thanks
