### ISSUE TITLE
registering a client with same website url dosn't show any message.... 

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-authorization-server#24]
...but it seems to be an issue because the former registered cliendt are not visible anymore. you need to logout and login again

**Comment by rahul-y** [comment]
This is because of the new UI. Client registration form is in bootstrap Collapsible panel and when a user registers any client with the same URL then it collapses.

**Comment by danielabutano** [comment]
@rahul-y  This is what I have in Firefox and Chrome too
![image](https://user-images.githubusercontent.com/1678179/63090455-3d1cd000-bf53-11e9-9f8e-6f017abc3551.png)
Just after registering the third client.
If I logout and login 
![image](https://user-images.githubusercontent.com/1678179/63090577-a43a8480-bf53-11e9-8e3c-1e0c2acc3610.png)
