### ISSUE TITLE
Not able to merge a user

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-authorization-server#25]
If I click yes, on the merge popup, I am redirected to http://localhost:8080/BioTestMine/login.do?merge=true which of course is wrong :(

**Comment by rahul-y** [comment]
Can you check your registered biotestmine client name?
IM auth server is redirecting user to http://localhost:8080/client-name/login.do

**Comment by danielabutano** [comment]
yes, my client name is BioTestMine. 
Is it only for local test purpouses? I suppose....

**Comment by danielabutano** [comment]
@rahul-y you can use URLGenerator class, somethink like that
`new URLGenerator(request).getPermanentBaseURL().append("/login")`
