### ISSUE TITLE
User name is not available

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-authorization-server#7]
I have created a user admin, registered a new client and because I've had some issues (which I think were related to the fact that I had deleted manually the client from db) I have:

1. deleted my db
2. created a new one
3. stopped the aouth server CTR+C
4. restarted java -jar target/authserver-0.0.1-SNAPSHOT.jar

The _user_ table is empty but when I try to create a new user with the same username admin I have an error message "User name is not available"

**Comment by rahul-y** [comment]
Once auth server is up that means it is connected with your database and without shutting it down we can't delete the database because Postgres doesn't allow this when database still has a connection with some user.
So I think your database has never been deleted.

**Comment by danielabutano** [comment]
You are right.
Unfortunally I have no messages from postgres client

```
postgres=# drop database "im-auth2";
DROP DATABASE
postgres=# create database "im-auth2";
CREATE DATABASE
postgres=# GRANT ALL PRIVILEGES ON DATABASE "im-oauth2" TO intermine;
GRANT
```

**Comment by danielabutano** [comment]
arhhh...my fault the application points to im-oauth2 NOT TO im-auth2
