### ISSUE TITLE
Selecting client id and secret id

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-authorization-server#9]
After registering a client, I would like to open it and select the fileds  client id and secret id in order to copy and pate into the biotestmine.properties file

**Comment by rahul-y** [comment]
I think this is already implemented.
When a user registers a client with IM auth server then on successful registration that user is redirected to a page from where it can copy clientId and secret form text area.
Also, that user can copy its clientId and secret from the registered Client page (List of all registered clients by that user)
Have I understood this issue right?

**Comment by danielabutano** [comment]
it works with chrome but not with firefox, I can't select those fields from the registered Client page (List of all registered clients by that user)
